apiVersion: v1
kind: Service
metadata:
  labels:
    app: petstore
  name: petstore
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: petstore
  type: LoadBalancer
